* tests/lha-test.in: filename should be contained in last error information.
git-svn-id: svn+ssh://svn.sourceforge.jp/svnroot/lha/lha/trunk@762 6a8cc165-1e22-0410-a132-eb4e3f353aba

diff --git a/tests/lha-test.in b/tests/lha-test.in
--- a/tests/lha-test.in
+++ b/tests/lha-test.in
@@ -34,12 +34,12 @@ check()
   typeset status=$1
   typeset lineno=$2
   if [[ $status -eq 0 ]]; then
-    echo    $FILENAME-$test_number ... ok >&2
-    echo    $FILENAME-$test_number ... ok at line $lineno
+    echo    "$FILENAME #$test_number ... ok" >&2
+    echo    "$FILENAME #$test_number ... ok at line $lineno"
   else
-    message $FILENAME-$test_number ... failed at line $lineno
+    message "$FILENAME #$test_number ... failed at line $lineno"
     ((error_num = error_num + 1))
-    error_tests="$error_tests #$test_number"
+    error_tests="$error_tests $FILENAME #$test_number"
     result=1
   fi
 }
